### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Peter230655** [tjstienstra/symmeplot#29]
In the example there is this line:

To convert the plot to a 2D variant, at the following line before scene.plot():

scene.as_orthogonal_projection_plot()

1.
On which plane will the 3D plot be projected? Can it be selected?

2.
There may be a typo: instead of ..., at the...
I think it should be ....., add the...

Thanks!

**Comment by tjstienstra** [comment]
> On which plane will the 3D plot be projected? Can it be selected?

As stated on [this line](https://github.com/tjstienstra/symmeplot/blob/394672727c30846a598f1b959f8bf402de9aa9ce/src/symmeplot/matplotlib/scene.py#L160) it is the YZ plane by default.

> There may be a typo: instead of ..., at the...
> I think it should be ....., add the...

Could you send a link to the location of this possible typo?

**Comment by Peter230655** [comment]
I saw it here:
![image](https://github.com/user-attachments/assets/64ad25d0-d164-4072-9f60-001d95a5523d)

which I got by clicking this link
https://tjstienstra.github.io/symmeplot/index.html

**Comment by tjstienstra** [comment]
Okay, that is indeed a typo in [this lin](https://github.com/tjstienstra/symmeplot/blob/main/docs%2Findex.rst#L64).

**Comment by Peter230655** [comment]
Small thing!
